CREATE TABLE IF NOT EXISTS PATIENTS (ID TEXT CHECK (typeof(ID) = 'text' OR ID IS NULL), GENDER TEXT CHECK (typeof(GENDER) = 'text' OR GENDER IS NULL), DECEASED_DATE TEXT CHECK (typeof(DECEASED_DATE) = 
'text' OR DECEASED_DATE IS NULL), DATE_OF_INCLUSION TEXT CHECK (typeof(DATE_OF_INCLUSION) = 'text' OR DATE_OF_INCLUSION IS NULL), DATE_OF_LAST_RESPONSE TEXT CHECK (typeof(DATE_OF_LAST_RESPONSE) = 'text' OR 
DATE_OF_LAST_RESPONSE IS NULL), BIRTHDATE TEXT CHECK (typeof(BIRTHDATE) = 'text' OR BIRTHDATE IS NULL), T2D_STATUS TEXT CHECK (typeof(T2D_STATUS) = 'text' OR T2D_STATUS IS NULL), T2D_ONSET_DATE TEXT CHECK 
(typeof(T2D_ONSET_DATE) = 'text' OR T2D_ONSET_DATE IS NULL), T1D_STATUS TEXT CHECK (typeof(T1D_STATUS) = 'text' OR T1D_STATUS IS NULL), T1D_ONSET_DATE TEXT CHECK (typeof(T1D_ONSET_DATE) = 'text' OR 
T1D_ONSET_DATE IS NULL), HYPERTENSION_STATUS TEXT CHECK (typeof(HYPERTENSION_STATUS) = 'text' OR HYPERTENSION_STATUS IS NULL), HYPERTENSION_STATUS_CODE TEXT CHECK (typeof(HYPERTENSION_STATUS_CODE) = 'text' 
OR HYPERTENSION_STATUS_CODE IS NULL), HYPERTENSION_ONSET_DATE TEXT CHECK (typeof(HYPERTENSION_ONSET_DATE) = 'text' OR HYPERTENSION_ONSET_DATE IS NULL), STROKE_STATUS TEXT CHECK (typeof(STROKE_STATUS) = 
'text' OR STROKE_STATUS IS NULL), STROKE_STATUS_CODE TEXT CHECK (typeof(STROKE_STATUS_CODE) = 'text' OR STROKE_STATUS_CODE IS NULL), STROKE_ONSET_DATE TEXT CHECK (typeof(STROKE_ONSET_DATE) = 'text' OR 
STROKE_ONSET_DATE IS NULL), UNIQUE(ID)  ) STRICT;
CREATE INDEX IF NOT EXISTS idx_patient_id ON PATIENTS (ID);
CREATE TABLE IF NOT EXISTS SMOKING (STATUS TEXT CHECK (typeof(STATUS) = 'text' OR STATUS IS NULL), STATUS_CODE TEXT CHECK (typeof(STATUS_CODE) = 'text' OR STATUS_CODE IS NULL), START_DATE TEXT CHECK 
(typeof(START_DATE) = 'text' OR START_DATE IS NULL), END_DATE TEXT CHECK (typeof(END_DATE) = 'text' OR END_DATE IS NULL), QUANTITY REAL CHECK (typeof(QUANTITY) = 'real' OR typeof(QUANTITY) = 'integer' OR 
QUANTITY IS NULL), PATIENTID TEXT) STRICT;
CREATE TABLE IF NOT EXISTS TOTAL_CHOLESTEROL (VALUE REAL CHECK (typeof(VALUE) = 'real' OR typeof(VALUE) = 'integer' OR VALUE IS NULL), UNIT TEXT CHECK (typeof(UNIT) = 'text' OR UNIT IS NULL), 
EFFECTIVE_DATE TEXT CHECK (typeof(EFFECTIVE_DATE) = 'text' OR EFFECTIVE_DATE IS NULL), PATIENTID TEXT) STRICT;
CREATE TABLE IF NOT EXISTS HDL_CHOLESTEROL (VALUE REAL CHECK (typeof(VALUE) = 'real' OR typeof(VALUE) = 'integer' OR VALUE IS NULL), UNIT TEXT CHECK (typeof(UNIT) = 'text' OR UNIT IS NULL), EFFECTIVE_DATE 
TEXT CHECK (typeof(EFFECTIVE_DATE) = 'text' OR EFFECTIVE_DATE IS NULL), PATIENTID TEXT) STRICT;
CREATE TABLE IF NOT EXISTS LDL_CHOLESTEROL (VALUE REAL CHECK (typeof(VALUE) = 'real' OR typeof(VALUE) = 'integer' OR VALUE IS NULL), UNIT TEXT CHECK (typeof(UNIT) = 'text' OR UNIT IS NULL), EFFECTIVE_DATE 
TEXT CHECK (typeof(EFFECTIVE_DATE) = 'text' OR EFFECTIVE_DATE IS NULL), PATIENTID TEXT) STRICT;
CREATE TABLE IF NOT EXISTS BLOODPRESSURE (EFFECTIVE_DATE TEXT CHECK (typeof(EFFECTIVE_DATE) = 'text' OR EFFECTIVE_DATE IS NULL), MEAN_UNIT TEXT CHECK (typeof(MEAN_UNIT) = 'text' OR MEAN_UNIT IS NULL), 
MEAN_VALUE REAL CHECK (typeof(MEAN_VALUE) = 'real' OR typeof(MEAN_VALUE) = 'integer' OR MEAN_VALUE IS NULL), SYSTOLIC_VALUE REAL CHECK (typeof(SYSTOLIC_VALUE) = 'real' OR typeof(SYSTOLIC_VALUE) = 'integer' 
OR SYSTOLIC_VALUE IS NULL), SYSTOLIC_UNIT TEXT CHECK (typeof(SYSTOLIC_UNIT) = 'text' OR SYSTOLIC_UNIT IS NULL), DIASTOLIC_UNIT TEXT CHECK (typeof(DIASTOLIC_UNIT) = 'text' OR DIASTOLIC_UNIT IS NULL), 
DIASTOLIC_VALUE REAL CHECK (typeof(DIASTOLIC_VALUE) = 'real' OR typeof(DIASTOLIC_VALUE) = 'integer' OR DIASTOLIC_VALUE IS NULL), PATIENTID TEXT) STRICT;
CREATE TABLE IF NOT EXISTS PLASMA_ALBUNIM (VALUE REAL CHECK (typeof(VALUE) = 'real' OR typeof(VALUE) = 'integer' OR VALUE IS NULL), UNIT TEXT CHECK (typeof(UNIT) = 'text' OR UNIT IS NULL), EFFECTIVE_DATE 
TEXT CHECK (typeof(EFFECTIVE_DATE) = 'text' OR EFFECTIVE_DATE IS NULL), PATIENTID TEXT) STRICT;
CREATE TABLE IF NOT EXISTS EGFR (VALUE REAL CHECK (typeof(VALUE) = 'real' OR typeof(VALUE) = 'integer' OR VALUE IS NULL), UNIT TEXT CHECK (typeof(UNIT) = 'text' OR UNIT IS NULL), EFFECTIVE_DATE TEXT CHECK 
(typeof(EFFECTIVE_DATE) = 'text' OR EFFECTIVE_DATE IS NULL), PATIENTID TEXT) STRICT;
CREATE TABLE IF NOT EXISTS HEMOGLOBIN (VALUE REAL CHECK (typeof(VALUE) = 'real' OR typeof(VALUE) = 'integer' OR VALUE IS NULL), UNIT TEXT CHECK (typeof(UNIT) = 'text' OR UNIT IS NULL), EFFECTIVE_DATE TEXT 
CHECK (typeof(EFFECTIVE_DATE) = 'text' OR EFFECTIVE_DATE IS NULL), PATIENTID TEXT) STRICT;
CREATE TABLE IF NOT EXISTS CREATININE (VALUE REAL CHECK (typeof(VALUE) = 'real' OR typeof(VALUE) = 'integer' OR VALUE IS NULL), EFFECTIVE_DATE TEXT CHECK (typeof(EFFECTIVE_DATE) = 'text' OR EFFECTIVE_DATE 
IS NULL), UNIT TEXT CHECK (typeof(UNIT) = 'text' OR UNIT IS NULL), PATIENTID TEXT) STRICT;
CREATE TABLE IF NOT EXISTS HBA1C (VALUE REAL CHECK (typeof(VALUE) = 'real' OR typeof(VALUE) = 'integer' OR VALUE IS NULL), EFFECTIVE_DATE TEXT CHECK (typeof(EFFECTIVE_DATE) = 'text' OR EFFECTIVE_DATE IS 
NULL), UNIT TEXT CHECK (typeof(UNIT) = 'text' OR UNIT IS NULL), PATIENTID TEXT) STRICT;
